Repository AY2324S1-CS2103T-T10-3/tp, pull requests merged in 2023-10, with the labels that each got.

#59 Update AboutUs
  docs/AboutUs.md
Labels: priority.low

#86 Branch v1.2
  src/main/resources/view/DarkTheme.css
Labels: type.task

#97 Edit Json structure
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
Labels: bug

#99 Modify save function
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: enhancement

#100 Update UI to 1.3a
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/ui/Calendar.java
  src/main/java/seedu/address/ui/DayCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CalendarList.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DayCard.fxml
  src/main/resources/view/MainWindow.fxml
Labels: enhancement

#101 Improve save function
  src/main/java/seedu/address/logic/commands/AddTimeCommand.java
  src/main/java/seedu/address/model/FreeTime.java
  src/main/java/seedu/address/model/Time.java
  src/main/java/seedu/address/model/TimeInterval.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTime.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: enhancement

#103 Add findGroup and findPerson commands
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindGroupCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: enhancement

#119 Fix time clash issue
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TimeInterval.java
  src/main/java/seedu/address/model/TimeIntervalList.java
Labels: bug

#122 Add ListGroup command
  src/main/java/seedu/address/logic/commands/ListGroupCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: enhancement
