Repository AY2324S1-CS2103T-T10-3/tp, pull requests merged in 2023-11, with the labels that each got.

#152 Fix bug
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/UngroupPersonCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteGroupTimeCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePersonTimeCommandTest.java
Labels: bug

#159 Change error messages in delete and find commands.
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ListTimeCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
Labels: bug

#160 Edit AddCommand Error Message
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/DeleteTimeCommandParser.java
Labels: bug

#161 Fix add time bug
  src/main/java/seedu/address/logic/commands/DeletePersonTimeCommand.java
  src/main/java/seedu/address/logic/parser/AddGroupMeetingTimeCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTimeCommandParser.java
  src/main/java/seedu/address/logic/parser/GroupRemarkCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TimeIntervalList.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteGroupTimeCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePersonTimeCommandTest.java
Labels: bug

#164 Improve code quality for delete and find command parsers
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: bug

#220 Update delete time message
  src/main/java/seedu/address/logic/commands/DeleteGroupTimeCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonTimeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTimeCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TimeIntervalList.java
Labels: documentation, priority.low

#224 Bug fixes
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/GroupPersonCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/GroupList.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTime.java
  src/test/java/seedu/address/storage/JsonAdaptedGroupTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTimeTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalGroups.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: bug

#227 Add remark to UG content table
  docs/UserGuide.md
Labels: documentation

#226 Update Developer's guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CreateGroupActivityDiagram.puml
  docs/diagrams/DeletePersonTimeActivityDiagram.puml
  src/main/java/seedu/address/logic/parser/GroupPersonCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteGroupTimeCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePersonTimeCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTimeTest.java
Labels: documentation

#234 Update PPP
  docs/team/zd292.md
Labels: documentation

#240 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/ComponentManagers.puml
  gradle.properties
Labels: documentation

#250 Fix check style
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/nicholastng010601.md
  gradlew
  gradlew.bat
  src/main/java/seedu/address/logic/parser/DeleteTimeCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TimeIntervalList.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteGroupTimeCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePersonTimeCommandTest.java
  src/test/java/seedu/address/logic/commands/UngroupPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddGroupCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTimeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/UngroupPersonCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedGroupTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTimeTest.java
  src/test/java/seedu/address/testutil/GroupBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TimeBuilder.java
  src/test/java/seedu/address/testutil/TimeIntervalBuilder.java
  src/test/java/seedu/address/testutil/TypicalGroups.java
  src/test/java/seedu/address/testutil/TypicalListOfGroupMates.java
  src/test/java/seedu/address/testutil/TypicalListOfTimeIntervals.java
  src/test/java/seedu/address/testutil/TypicalTimeIntervals.java
Labels: documentation

#251 Update DG
  docs/DeveloperGuide.md
  docs/team/nicholastng010601.md
  src/main/java/seedu/address/model/TimeIntervalList.java
Labels: documentation

#258 Edit PPP
  docs/team/nicholastng010601.md
Labels: documentation

#259 Fix errors in UG
  docs/UserGuide.md
Labels: documentation

#264 Add diagrams
  docs/diagrams/AddGroupMeetingTimeSequenceDiagram.puml
  docs/diagrams/AddTimeActivityDiagram.puml
  docs/diagrams/CreateGroupActivityDiagram.puml
  docs/diagrams/DeletePersonTimeActivityDiagram.puml
  docs/diagrams/DeletePersonTimeDiagram.puml
  docs/diagrams/GroupPersonActivityDiagram.puml
  docs/diagrams/GroupRemarkSequenceDiagram.puml
  docs/diagrams/ListTimePersonSequenceDiagram.puml
  docs/diagrams/UngroupPersonSequenceDiagram.puml
Labels: documentation

#262 Update UserGuide
  docs/UserGuide.md
  docs/box.html
  docs/images/features/Generalcommand_clear.png
  docs/images/features/Generalcommand_help.png
  docs/images/features/Managecontacts_add.png
  docs/images/features/Managecontacts_addwithg.png
  docs/images/features/Managecontacts_delete.png
  docs/images/features/Managecontacts_find.png
  docs/images/features/Managecontacts_list.png
  docs/images/features/Managegroup_delete.png
  docs/images/features/Managegroup_find.png
  docs/images/features/Managegroup_group.png
  docs/images/features/Managegroup_listgroup.png
  docs/images/features/Managegroup_new.png
  docs/images/features/Managegroup_remark.png
  docs/images/features/Managegroup_ungroup.png
  docs/images/features/Managetime_addmeeting.png
  docs/images/features/Managetime_addtime.png
  docs/images/features/Managetime_deletetimecontact.png
  docs/images/features/Managetime_deletetimegroup.png
  docs/images/features/Managetime_findfreetime.png
  docs/images/features/Managetime_listtimecontact.png
  docs/images/features/Managetime_listtimegroup.png
  src/main/java/seedu/address/logic/commands/GroupPersonCommand.java
  src/main/java/seedu/address/logic/parser/GroupPersonCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/GroupList.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/GroupPersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/GroupPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/ListGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/UngroupPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/GroupPersonCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalGroups.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: documentation

#268 Edit DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteGroupSequenceDiagram.puml
  docs/diagrams/FindPersonSequenceDiagram.puml
  docs/diagrams/ListGroupSequenceDiagram.puml
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java
Labels: documentation

#274 Branch v1.4
  docs/UserGuide.md
Labels: documentation

#282 Edit DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/images/UG/QUICKSTART2.png
  docs/images/UG/QuickStart1.png
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/TimeIntervalList.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: documentation

#285 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/FindFreeTimeActivityDiagram.puml
  docs/diagrams/FindFreeTimeSequenceDiagram.puml
  docs/team/johndoe.md
  docs/team/zd292.md
Labels: documentation

#289 Update Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindFreeTimeActivityDiagram.puml
  docs/diagrams/FindFreeTimeSequenceDiagram.puml
  docs/team/johndoe.md
  docs/team/zd292.md
Labels: documentation

#296 Update Developer Guide
  docs/diagrams/FindFreeTimeSequenceDiagram.puml
  docs/diagrams/GroupPersonSequenceDiagram.puml
  docs/diagrams/UngroupPersonSequenceDiagram.puml
Labels: documentation

#306 Fix UG inconsistencies
  docs/UserGuide.md
Labels: documentation
